plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs24.github.io/w23 
baseurl: "/w23"  
instructor: "Diba Mirza"
name: "CS24 Winter 2023"
course: "CS24"
course_title: "Problem Solving with Computers II"
title: "UCSB CS24 W23"
github_url: https://github.com/ucsb-cs24/w23
qtr: "W23"
quarter: "Winter 2023"
lecture_times: "MW 12:30pm - 1:45pm"
lecture_location: "NH 1006"
lab_times: "Thursdays: 9a, 10a, 11a, 12p, 1p"
tas: "Samridhi	Maheshwari, Tyler	Ekaireb, Huanhua	Xu, Lijuan	Cheng, Kaiwen	Li"
ulas: "Rachel Jiang and Zack Glazewski"
class_org:
   name: ucsb-cs24-w23
   url: https://github.com/ucsb-cs24-w23
   githublinker: CS24 W23
   
lect_repo: https://github.com/ucsb-cs24-w23/cs24-w23-lectures
start_week: 1
start_date: 2023-01-08
num_weeks: 10
extra_exam_week: true

instructor_url: https://ucsb-cs24.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2023-01-09" },
  {"label":"ZyBook Ch 11 & 12 activities due at 11:59p", "date":"2023-01-13" },
  {"label":"ZyBook Ch 13 & 14 activities due at 11:59p", "date":"2023-01-20" },
  {"label":"ZyBook Ch 15, 16, & 17  activities due at 11:59p", "date":"2023-01-27" },
  {"label":"ZyBook Ch 18, 19, & 20  activities due at 11:59p", "date":"2023-02-03" },
  {"label":"ZyBook Ch 21 & 22  activities due at 11:59p", "date":"2023-02-10" },
  {"label":"ZyBook Ch 23  activities due at 11:59p", "date":"2023-02-17" },
  {"label":"ZyBook Ch 24 activities due at 11:59p", "date":"2023-02-24" },
  {"label":"ZyBook Ch 25 & 26 activities due at 11:59p", "date":"2023-03-03" },
  {"label":"ZyBook Ch 27  activities due at 11:59p", "date":"2023-03-10" },
  {"label":"ZyBook Ch 28  activities due at 11:59p", "date":"2023-03-17" },
  {"label":"Drop deadline (no W grade)","date":"2023-02-23" },
  {"label":"Univ Holiday (MLK Jr. Day) - No lecture", "date":"2023-01-16" },
  {"label":"Univ Holiday (Presidents' Day) - No lecture", "date":"2023-02-20" },
  {"label":"W23 Instruction Ends", "date":"2023-03-17" },  
  {"label":"Final Exam: noon - 3PM", "date":"2023-03-21" },
  {"label":"W23 Quarter Ends", "date":"2023-03-24" }          
  ]

kramdown:
   parse_block_html: true

exclude:
   - vendor
include:
  - _pages

timezone: America/Los_Angeles

collections:
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  pa:
    output: true
    permalink: /pa/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout

theme: jekyll-theme-cayman
